### ISSUE TITLE
Is it the official repo for the paper?

### ISSUE THREAD

**Issue by ryushinn** [leisuzz/Highlight-Aware-Two-Stream-Network-for-Single-Image-SVBRDF-Acquisition#1]
Hi,

I am curious if this repo is the official repo for the paper "Highlight-aware two-stream network for single-image SVBRDF acquisition"? 

If yes, would you plan to release the pre-trained weights used to produce results in the paper?

Thanks!

**Comment by leisuzz** [comment]
Sorry, it’s not the official repo for the paper

**Comment by ryushinn** [comment]
I see, thanks for replying.
